-- 创建表格的 DDL
CREATE TABLE agents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    provider_entered_business_name VARCHAR(255) NOT NULL,
    business_address VARCHAR(255),
    business_suburb VARCHAR(100),
    business_state VARCHAR(50),
    business_country VARCHAR(100)
);

-- 插入数据的 DML
INSERT INTO agents (provider_entered_business_name, business_address, business_suburb, business_state, business_country) VALUES
('AMES Group (Australian Management and Education Services Pty Ltd)', '803/368, Sussex Street', 'Sydney', 'NSW', 'Australia'),
('VM Consultancy and Visa Services', 'level 5, 161 Collins Street', 'Melbourne', 'VIC', 'Australia'),
('316 Pty Ltd', '306/343 Little Collins Street', 'MELBOURNE', 'VIC', 'Australia'),
('365 International service group Pty Ltd', 'China', 'China', 'China', 'China'),
('A Class Immigration and Education Consultants', '7/334 Hume Highway', 'Craigieburn', 'VIC', 'Australia'),
('Andino Education Group', '49 White Street, Parkville', 'Docklands', 'VIC', 'Australia'),
('A1 Education & Migration Services', '45 BYRON RD', 'GUILDFORD', 'NSW', 'Australia'),
('AB Consultants', '69 Askari Complex Bedian Road', 'Lahore Cantt', 'Lahore', 'Pakistan'),
('AC Oceania Consulting Pty Ltd', '292 Clayton road', 'Clayton', 'VIC', 'Australia'),
('ACCESS EDUCATION & MIGRATION INTERNATIONAL PTY. LTD.', '140 Bourke Street', 'Melbourne', 'VIC', 'Australia'),
('ACEA Global', '36 Shawlands Drive', 'Tullamarine', 'VIC', 'Australia'),
('ACG Group Trust', '1505/18 Hoff Boulevard, Southbank', 'Southbank', 'VIC', 'Australia'),
('ACIC Melbourne', 'Level 15, 190 Queen St', 'Melbourne', 'VIC', 'Australia'),
('Active Study Australia', '2/32 Buckingham DR. Wangara 6065', 'Perth', 'WA', 'Australia'),
('Advanced Global Study', 'Figari Office #22 at Lvl17 Collins Square Tower 4 Dockland. VIC 3008', 'Dockland', 'VIC', 'Australia'),
('ADVISE 365 (GLOBAL) PTY LTD', '133 Church Street,', 'Parramatta', 'VIC', 'Australia'),
('AES - Australia Education Services Pty Ltd (Melbourne-Head Office)', 'Unit 905, 401 Docklands Dr', 'Docklands', 'VIC', 'Australia'),
('Andino Education Group', 'A''beckett Street', 'Melbourne', 'VIC', 'Australia'),
('AOJI Education Australia Pty Ltd', 'Suite 1, Level 5 94 Elizabeth Street', 'Melbourne', 'VIC', 'Australia'),
('AOYU Consulting Pty Ltd', 'Level 4, 155 Queen St', 'Melbourne', 'VIC', 'Australia'),
('AS Global Education (AS Global Education Consultants Pty Ltd)', '13 Steen Avenue', 'Wollert', 'VIC', 'Australia'),
('Au-Assess Education Service', 'Shop 1 294 High Street', 'Preston', 'VIC', 'Australia'),
('Ausky Migration & Education Pty Ltd', 'level 1, 91 Gouger St', 'Adelaide', 'SA', 'Australia'),
('Aussie - ASEAN Education & Immigration Services', 'Suite 411, Level 4, 365 Little Collins Street', 'Melbourne', 'VIC', 'Australia'),
('Aussie Education Group Pty Ltd.', '522/368 Sussex Street', 'Sydney', 'NSW', 'Australia'),
('Austop Capital Holdings Pty Ltd', 'Suite 15, Level 15, 327 Pitt Street', 'Sydney', 'NSW', 'Australia'),
('Australia Education Group Pty Ltd (Australia Education Group)', 'Suite #1005, Level 10/55 Swanston Street', 'Melbourne', 'VIC', 'Australia'),
('Australia M.Z. Holdings Pty', 'Level 12, 350 Collins Street', 'MELBOURNE', 'VIC', 'Australia'),
('Australia Visa Link Pty Ltd - Melbourne (HQ)', 'Suite 2,Level5/190  Queen Street, Melbourne', 'MELBOURNE', 'VIC', 'Australia'),
('Australia Wisdom Global Group Pty Ltd', '3145 120 Collins St.', 'Melbourne', 'VIC', 'Australia'),
('AustraliaMigrate', 'Suite 601, 10 Help Street, Chatswood, NSW 2067', 'Chatswood', 'NSW', 'Australia'),
('Australian Education Expert - PFEC Global', 'L 12/50 Queen St', 'Melbourne', 'VIC', 'Australia'),
('Auswin International Group', 'Suite 509, Level 5 343 Little Collins Street', 'Melbourne', 'VIC', 'Australia'),
('Bansal Education Group', 'Suite 701, Level 7/343 Little Collins St 288 Spencer Street', 'Melbourne', 'VIC', 'Australia'),
('Beacon Education & Migration', 'Level 3, 488 Bourke Street', 'Melbourne', 'VIC', 'Australia'),
('Best Education Services Australia', 'Suite 801-803, Level 8, 258 Little Bourke', 'Melbourne', 'VIC', 'Australia'),
('Best Muffin Pty Ltd (T/A International Immigration services)', 'Melbourne', 'Melbourne', 'VIC', 'Australia'),
('Best Partner Education', 'Australia Square 3301 L 33, 264 George Street', 'Sydney', 'NSW', 'Australia'),
('Beyon Education', '28 Ironbark Dr', 'TEMPLESTOWE LOWER', 'VIC', 'Australia'),
('COACH Education & Migration Services', '43B Haldon St', 'Lakemba', 'NSW', 'Australia'),
('Discover Education Australia', '1009, 55 Swanston Street', 'Melbourne', 'VIC', 'Australia'),
('DOWN UNDER EDUCATION Pty Ltd', 'Level 23, Tower 5 Collins Square 727 Collins Street', 'Docklands', 'VIC', 'Australia'),
('Dream Overseas Pty Ltd', 'Room 809, No. 250 Hualin Road,', 'Fuzhou', 'Fujian', 'China'),
('Edu Pathways Group', 'Level 9, 474 Flinders street', 'Melbourne', 'VIC', 'Australia'),
('Education Information Center', 'Suite 1, level 13 55 Swanston Street', 'Melbourne', 'VIC', 'Australia'),
('EEVS Melbourne Pty Ltd', 'level 3/313 Flinders Ln', 'MELBOURNE', 'VIC', 'Australia'),
('Elegance Education Consultancy Pty Ltd', '8 Treeton Drive Wollert', 'Melbourne', 'VIC', 'Australia'),
('Elevate Migration', '74 McCorry Drive', 'Collingwood park', 'QLD', 'Australia'),
('EMK GLOBAL PTY LTD', 'Level 3, 58 Kitchener Parade', 'Bankstown', 'NSW', 'Australia'),
('Endeavour Education & Migration Consultants', 'Level 1/470 Collins Sreet', 'Melbourne', 'VIC', 'Australia'),
('ESI Global Services', '9/155,', 'Castlereagh street', 'NSW', 'Australia'),
('Executive Consultancy Australia', 'Unit 201, Tower C, The Regalia Park Towers, P. Tuazon Avenue', 'Cubao, Quezon City', 'MANILA', 'Philippines'),
('Expert Education and Visa Services', 'Suite 5, Level 1, 224 Lonsdale Street', 'Dandenong', 'VIC', 'Australia'),
('Express Study Solution', '148 Elizabeth Street', 'Sydney', 'NSW', 'Australia'),
('Femeda Consultants', 'Suite 437, 1 Queens Road', 'Melbourne', 'VIC', 'Australia'),
('First Source World', '27/2 O''CONNELL ST', 'PARRAMATTA', 'NSW', 'Australia'),
('Fitri, Liana (Seven Peaks Education)', '1216A/87-89 Liverpool Street', 'Sydney', 'NSW', 'Australia'),
('FOUR A EDUCATION', 'China', 'China', 'China', 'China'),
('Francis Global Education', 'Melbourne', 'Melbourne', 'VIC', 'Australia'),
('Fujian Pearson Oversea Information Consulting Co.,LTD', '12C1, Xinduhui Financial Plaza, No.43 East Street, Gulou District', 'Fuzhou', 'Fujian', 'China'),
('Future Care Consultants Pty Ltd', 'Level 39, 385 Bourke Street', 'Melbourne', 'VIC', 'Australia'),
('GAWSOME CONSULTING PTY LTD', '30 TIMBERTOPRD, RINGWOOD NORTH, VIC, 3134', 'RINGWOOD NORTH', 'VIC', 'Australia'),
('GEM Education Consultancy Australia', 'Unit 16/1219-1221 Riversdale Rd', 'Box Hill South', 'VIC', 'Australia'),
('Genuine Education & Visa Services', '2.14/365 Little Collins Street', 'Melbourne', 'VIC', 'Australia'),
('Get Qualified Now', 'Level 7 Bourke Street', 'Melbourne', 'VIC', 'Australia'),
('Global Alliance Education and Migration Consultant (ECA-Agent)', 'Suite 2 Leve 7/38 Currie Street', 'Adelaide', 'SA', 'Australia'),
('Global Mate', '14J Level 1 218 Padstow Road', 'Eight Mile Plains', 'QLD', 'Australia'),
('Golden Leaf Group Pty Ltd', 'Suite 10 1 Main Street', 'Box Hill', 'VIC', 'Australia'),
('Gradpath Education Consultants Pty Ltd', '92 Townley Boulevard, Werribee. VIC 3030', 'Werribee', 'VIC', 'Australia'),
('H GUO & Y LIN', 'Suite 437, 1 Queens Road', 'Melbourne', 'VIC', 'Australia'),
('HMMK MIGRATION', '17 HALDON ST', 'LAKEMBA', 'NSW', 'Australia'),
('iCan Education Pty Ltd', '13/278 sussex st., Sydney, NSW 2000', 'Sydney', 'NSW', 'Australia'),
('ICS International Education and MigrationICS International Education and Migration (ECA-Agent)', 'Suite 207 / 365 Little Collins St', 'Melbourne', 'VIC', 'Australia'),
('IMMI Centre Pty Ltd.', 'Level 1, 4 Railway Parade,', 'Burwood', 'NSW', 'Australia'),
('International Migration Consultants', 'House No. 21', 'Lahore', 'Punjab', 'Pakistan'),
('Iris Zhang', 'Melbourne', 'Melbourne', 'VIC', 'Australia'),
('iWise Education Pty, Ltd', '203/365 Lt Collins Street', 'Melbourne', 'VIC', 'Australia'),
('J & R GLOBAL CONSULTING', 'Melbourne', 'Melbourne', 'VIC', 'Australia'),
('JJF Migration Consultancy', 'Level 1, Suite 22 797 Plenty Road', 'South Morang', 'VIC', 'Australia'),
('JKM GROUP (AUS) PTY LTD (SYNCHRO THINK CONSULTANCY)', 'Suite 23 7-9 Leeds Street, Footscray', 'Melbourne', 'VIC', 'Australia'),
('JLH Consultantancy Services', 'The World Trade Centre, Tower 4 Unit 1028, Level 10, 611 Flinders Street', 'MELBOURNE', 'VIC', 'Australia'),
('JLL Migration & Education Pty Ltd (Australia) (Melbourne) (Head Office)', 'Level 4, 155 Queen Street', 'Melbourne', 'VIC', 'Australia'),
('Kandel Consultant Pty Ltd', 'Level 10, 230 Collins Street', 'Melbourne', 'VIC', 'Australia'),
('LYNX GLOBAL', '68, La Trobe St', 'Melbourne', 'VIC', 'Australia'),
('M & Z consultancy', 'Melbourne', 'Melbourne', 'VIC', 'Australia'),
('MERCHANTS OF PROSPERITY PTY LTD', 'Level1, 255 Bourke Street', 'Melbourne', 'VIC', 'Australia'),
('MG & PA GROUP PTY LTD', 'Suite 7.10, Level 7, 365 Little Collins Street', 'Mebourne', 'VIC', 'Australia'),
('Millennium Consultants', 'Suite 404, Level 4, 365 Little Collins Street', 'Melbourne', 'VIC', 'Australia'),
('Miracle Migration and Education', 'Level 1 suite 12/785 Pascoe Vale Rd,', 'Glenroy', 'VIC', 'Australia'),
('MY EDUCATION SPECIALISTS PTY LTD', '442 Elizabeth Street', 'Melbourne', 'VIC', 'Australia'),
('MyAusVisa', 'Level 6, Suite 609, 368 Sussex Street', 'Sydney', 'NSW', 'Australia'),
('New Horizon Migration And Education Solutions', 'Suite 710 Level 7 365 Little Collins Street', 'Melbourne', 'VIC', 'Australia'),
('New Oriental Vision Overseas Consulting Australia Pty Ltd (Australia) (Melbourne)', 'Level 4, 152 Elizabeth Street', 'Melbourne', 'VIC', 'Australia'),
('Neway Consulting', '432 Burwood Road', 'Hawthorn', 'VIC', 'Australia'),
('NewEdge Consultancy (Australia) (Melbourne)', 'Level 3, 257 Collins Street', 'Melbourne', 'VIC', 'Australia'),
('Newpoint Migration and Business Consulting', 'Level 1203, 350 Collins Street', 'MELBOURNE', 'VIC', 'Australia'),
('NOLIMIT EDUCATION PTY LTD', 'Level 9 440 Collins Street', 'Melbourne', 'VIC', 'Australia'),
('NORWEST EDUCATION PTY LTD', '68 Barina Downs Road,', 'NORWEST', 'NSW', 'Australia'),
('Oceania Consultants Pty Ltd', 'Suite 308 Level 3, Fayworth House 379-383 Pitt Street', 'Sydney', 'NSW', 'Australia'),
('OMA Pty Ltd (OZ-FIL International Education Services)', '118 Fiorelli Boulevard', 'Cranbourne East', 'VIC', 'Australia'),
('Optimistic Consultants', '5 Central Grove', 'Broadmeadows', 'VIC', 'Australia'),
('Owlet Groups Pty Ltd', '1/861 Sydney Road', 'Brunswick', 'VIC', 'Australia'),
('Oxford Migration Pty Ltd', '12 Brunswick Dr,', 'Truganiana', 'VIC', 'Australia'),
('Oz Pacific Group', 'Level 3, Suite 33, 181 Church Street', 'Parramatta', 'NSW', 'Australia'),
('Oz World Migration Consultants', 'Suite 1408, Level 14, 227 Collins Street', 'Melbourne', 'VIC', 'Australia'),
('OZ-Fil Int''l Education Services', '2/10 Tarene Street', 'Dandenong', 'VIC', 'Australia'),
('Ozpathway Pty Ltd', 'Level 2, 407-409 Swanston St', 'Melbourne', 'VIC', 'Australia'),
('Panda International Consulting Pty Ltd', 'Suite 510, 530 Little Collins Street', 'Melbourne', 'VIC', 'Australia'),
('Paragon Education Group', 'Century Building Level 5 125 Swanston Street', 'Melbourne', 'VIC', 'Australia'),
('Qingdao ZX International E&T Cooperation', 'SHOP 2, 408 King William Street', 'Adelaide', 'SA', 'Australia'),
('RACC Australia', 'Suite 715-716, Level 7  343 Little Collins Street', 'Melbourne', 'VIC', 'Australia'),
('Rightway Airlinks Pty Ltd', 'Suite 105B, 530 Little Collins Street', 'Melbourne', 'VIC', 'Australia'),
('RK Education and Visa Services Pty Ltd', 'Suite 6.09, Level 6, 365 Little Collins St', 'Melbourne', 'VIC', 'Australia'),
('Roo Edu', 'Level 7 276 Flinders Street', 'MELBOURNE', 'VIC', 'Australia'),
('Royal International Migration & Education Consultants', 'Address 87 Wigram Street, Harris Park, NSW 2150', 'Harris Park', 'NSW', 'Australia'),
('RPS Migration Pty Ltd', 'Suite 1 Level 7 470 Collins Street', 'Melbourne', 'VIC', 'Australia'),
('Sam Aus Education', 'melbourne', 'melbourne', 'VIC', 'Australia'),
('Sarika', 'Melbourne', 'Melbourne', 'VIC', 'Australia'),
('SK Education Group Pty. Ltd.', 'level 2, Ellingwood Parade', 'Boxhill', 'VIC', 'Australia'),
('Sogo Visa and Education', '250 Collins St', 'Melbourne', 'VIC', 'Australia'),
('Songcheng', 'Melbourne', 'Melbourne', 'VIC', 'Australia'),
('STU GLOBAL PTY LTD', '1 13 Arnold Grove', 'Doncaster', 'VIC', 'Australia'),
('Student Guide Australia', '40/140 William Street', 'Melbourne', 'VIC', 'Australia'),
('Studyhut Consultants Pty Ltd', '195 Victoria Parade', 'Suva', 'Suva', 'Fiji'),
('Success Education Services', '70 Jalan Nuri Indah 2 Taman Nuri Indah', 'Seremban', 'Negeri Sembilan', 'Malaysia'),
('SUMMIT MIGRATION AND EDUCATION', 'Suite 908/530 Little Collins Street', 'Melbourne', 'VIC', 'Australia'),
('T & N Sydney International Education Consultancy Pty Ltd', 'Suite 12, 265 - 273 Illawarra Road', 'Marrickville', 'NSW', 'Australia'),
('TATA Education Service Pty Ltd', 'Level 14, Melbourne Central Tower, 360 Elizabeth St', 'Melbourne', 'VIC', 'Australia'),
('The Lakhani Family Trust T/A Vision Consultants Australia Pty Ltd', 'Suite 7A and 7B, Level 5,, 1 Elizabeth Street', 'Melbourne', 'VIC', 'Australia'),
('The Newstone Group Pty Ltd', 'Level 7 440 Elizabeth Street', 'Melbourne', 'VIC', 'Australia'),
('Themigration.com.au trading for(Aussie Migration and Education services Pty Ltd )', 'Level 15, 60 Station St East', 'PARRAMATTA', 'NSW', 'Australia'),
('Think Higher Consultants T/A Think Higher Pty Ltd', 'Level 3,105 Queens Street', 'Melbourne', 'VIC', 'Australia'),
('Three Enterprises Pty Ltd T/A Tricon Consulting Group', 'Suite 506, Level 5, 55 Swanston Street', 'Melbourne', 'VIC', 'Australia'),
('TRUTH MIGRATION AND EDUCATION CONSULTANCY PTY LTD', '171 Latrobe Street', 'Melbourne', 'VIC', 'Australia'),
('Unikey Global Pty Ltd', 'Suite 1603, 530 Little Collins Street', 'Melbourne', 'VIC', 'Australia'),
('V1 Overseas Careers Pty Ltd', '2 Trevino Close', 'Hoppers Crossing', 'VIC', 'Australia'),
('Vantage Consultants Pty. Ltd.', '3, 313 Flinders Lane', 'Melboure', 'VIC', 'Australia'),
('VIBRANT EDUCATIONAL CONSULTANT(PRIVATE) LIMITED COMPANY', 'MUSLIM BIN AQEEL COLONY STREET NO.08 OFFICE NO.04 SAHIWAL, PUNJAB PAKISTAN', 'AQEEL COLONY', 'PUNJAB', 'Pakistan'),
('Visa Advice Service', 'Melbourne', 'Melbourne', 'VIC', 'Australia'),
('Waterstone Consulting Pty Ltd', '9/1091 Stud Rd', 'ROWVILLE', 'VIC', 'Australia'),
('Zhenghe Consulting Australia', 'Suite 2.01B Level 2/ 19-23 Prospect Street', 'Box Hill', 'Victoria', 'Austria'),
('ZTA Education Consultants', 'Suite 13, 55 Swanston Street', 'Melbourne', 'VIC', 'Australia');
